GET http://localhost:5000


###find all
GET http://localhost:5000/devices


###search by name
GET http://localhost:5000/devices?name=Device12

###search by parentName
GET http://localhost:5000/devices?parentName=Device2

### Update a product by name
PATCH  http://localhost:5000/devices/edit?name=Device12
Content-Type: application/json

{
  "Power": 5965
}

### Delete a product by name
DELETE  http://localhost:5000/devices/delete/Device2

### Create a product
POST http://localhost:5000/devices/create
Content-Type: application/json

{
    "name": "Device12",
    "parentName": "Device9",
    "Voltage": 94,
    "Power": 4126
}

###
GET http://localhost:5000/chatbox